"""Channel-specific response formatting for the Customer Success FTE."""


def format_for_email(response: str, ticket_id: str = "", customer_name: str = "Customer") -> str:
    """Format response for email channel - formal with greeting/signature."""
    return f"""Dear {customer_name},

Thank you for reaching out to TechCorp Support.

{response}

If you have any further questions, please don't hesitate to reply to this email.

Best regards,
TechCorp AI Support Team
---
Ticket Reference: {ticket_id}
This response was generated by our AI assistant. For complex issues, you can request human support."""


def format_for_whatsapp(response: str) -> str:
    """Format response for WhatsApp channel - concise and conversational."""
    if len(response) > 300:
        response = response[:297] + "..."
    return f"{response}\n\nReply for more help or type 'human' for live support."


def format_for_web(response: str) -> str:
    """Format response for web form channel - semi-formal."""
    return f"""{response}

---
Need more help? Reply to this message or visit our support portal."""


def format_response(response: str, channel: str, **kwargs) -> str:
    """Format response based on channel type."""
    if channel == "email":
        return format_for_email(
            response,
            ticket_id=kwargs.get("ticket_id", ""),
            customer_name=kwargs.get("customer_name", "Customer"),
        )
    elif channel == "whatsapp":
        return format_for_whatsapp(response)
    else:
        return format_for_web(response)
